<?php

/**
 * @file
 * Contains workwise.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function workwise_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the workwise module.
    case 'help.page.workwise':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integrate Drupal 8 with the WorkWise ERP') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_presave().
 */
function workwise_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  /** @var \Drupal\workwise\WorkWiseIntegrationManagerInterface $manager */
  $manager = \Drupal::service('workwise_integration.manager');

  $integrations = $manager->getIntegrationsForEntityType($entity->getEntityTypeId());

  // @todo check if integration already saved, and either create or update.
}
