name: topfloorcommercedemo
recipe: pantheon
config:
  framework: drupal8
  site: topfloor-commerce-demo
  id: b51a212d-9a69-47ce-a950-38fef729a10d
tooling:
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
