workwise.workwise_plugin:
  type: mapping
  label: 'WorkWise plugin configuration'
  mapjping: {}

workwise.workwise_connection.*:
  type: config_entity
  label: 'WorkWise connection'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    url:
      type: uri
      label: 'WorkWise URL'
    company:
      type: string
      label: 'Company'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
    enabled:
      type: boolean
      label: 'Enabled'

workwise.workwise_integration.*:
  type: config_entity
  label: 'WorkWise integration'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    connection_id:
      type: string
      label: 'Connection ID'
    plugin_id:
      type: string
      label: 'Plugin ID'
    plugin_configuration:
      type: workwise.workwise_plugin
      label: 'Plugin configuration'
    enabled:
      type: boolean
      label: 'Enabled'
