enabled_pages: {  }
reload_on_success: false
dialog_width: 480
dialog_height: auto
create_profile_after_registration: false
profile_type: customer
hide_field_descriptions: false
header_blocks: {  }
footer_blocks: {  }
_core:
  default_config_hash: sJoXmaMmB3Nwd8-q46lzcLZlLrQJ1HaiXuD5Ys5zYMY
