aluminum_copyright_block:
  copyright_text: 'Copyright [date:custom:Y] [site:name]. All rights reserved.'
aluminum_follow_block:
  facebook_enabled: true
  facebook_weight: 10
  twitter_enabled: true
  twitter_weight: 20
  linkedin_enabled: true
  linkedin_weight: 30
  youtube_enabled: true
  youtube_weight: 40
  google_plus_enabled: true
  google_plus_weight: 50
aluminum_phone_number_block:
  phone_number_type: phone_number
aluminum_link_list_block:
  links: ''
aluminum_content_fields_block:
  content_fields: ''
_core:
  default_config_hash: 25zGoQErdcBOptFIW7RaAwy2chlgm0Bfm7kOouwmC50
