module:
  account_modal: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  aluminum: 0
  aluminum_blocks: 0
  aluminum_storage: 0
  block: 0
  block_content: 0
  breakpoint: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor: 0
  color: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_cart_blocks: 0
  commerce_checkout: 0
  commerce_combine_carts: 0
  commerce_log: 0
  commerce_order: 0
  commerce_payment: 0
  commerce_payment_example: 0
  commerce_price: 0
  commerce_product: 0
  commerce_promotion: 0
  commerce_shipping: 0
  commerce_store: 0
  commerce_tax: 0
  components: 0
  config: 0
  config_direct_save: 0
  config_update: 0
  config_update_ui: 0
  contact: 0
  contact_emails: 0
  contact_storage: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  devel: 0
  diff: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  facets: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_browser: 0
  filter: 0
  float_labels: 0
  help: 0
  history: 0
  hook_event_dispatcher: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  linkit: 0
  login_emailusername: 0
  mailsystem: 0
  me_redirect: 0
  media: 0
  menu_block: 0
  menu_link_attributes: 0
  menu_trail_by_path: 0
  menu_ui: 0
  name: 0
  node: 0
  options: 0
  page_cache: 0
  pantheon_advanced_page_cache: 0
  path: 0
  physical: 0
  profile: 0
  quickedit: 0
  r4032login: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  responsive_tables_filter: 0
  robotstxt: 0
  search: 0
  search_api: 0
  search_api_db: 0
  settings_tray: 0
  shortcut: 0
  simple_block: 0
  state_machine: 0
  statistics: 0
  swiftmailer: 0
  swiftmailer_force_html: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  video_embed_wysiwyg: 0
  views_block_filter_block: 0
  views_menu_children_filter: 0
  views_pager_summary: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  adminimal_theme: 0
  spacelift: 0
  goodway: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
