features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: themes/goodway/images/logo.png
favicon:
  use_default: 0
  path: themes/goodway/favicon.ico
_core:
  default_config_hash: sPAOPlc2IYr-adm_8i75dUSb5OyfjEaqXQUP1JMxpMg
